# Site settings
title: Helmet Animations
tagline: Traditional Animator, Digital Artist, Graphic Design Student
description: Portfolio
image: /assets/images/image.gif
url: https://helmetanimations.github.io
sidebar_main_text: 
home_url: /portfolio/
cover_text: Check my Website!
author: Helmet Animations
lang: en-US
google_analytics: 
logo: /favicon.ico
twitter:
  username: Helmet Animations
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/imageLogo.gif

# Build settings
remote_theme: wildleoknight/stardust 
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap